<?php





$SHEMA3 =
array(
		array(
			array("RYAD"=>"EMPTY", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR", "COLSPAN"=>"8"),
			array("RYAD"=>"АМФИТЕАТР", "NUM"=>"PRINT_DATA", "TYPE_PLACE"=>"AMFITEATR", "COLSPAN"=>"22"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR", "COLSPAN"=>"8"),
		),
		array(
			array("RYAD"=>"22", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"22", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"22", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"22", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"22", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"22", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"22", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"22", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"22", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"22", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"22", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"22", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"22", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"22", "NUM"=>"1", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"22", "NUM"=>"2", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"22", "NUM"=>"3", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"22", "NUM"=>"4", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"22", "NUM"=>"5", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"22", "NUM"=>"6", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"22", "NUM"=>"7", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"22", "NUM"=>"8", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"22", "NUM"=>"9", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"22", "NUM"=>"10", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"22", "NUM"=>"11", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"22", "NUM"=>"12", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"22", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"22", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"22", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"22", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"22", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"22", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"22", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"22", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"22", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"22", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"22", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"22", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"22", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
		),
		array(
			array("RYAD"=>"21", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"21", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"21", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"21", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"21", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"21", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"21", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"21", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"21", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"21", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"21", "NUM"=>"1", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"21", "NUM"=>"2", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"21", "NUM"=>"3", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"21", "NUM"=>"4", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"21", "NUM"=>"5", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"21", "NUM"=>"6", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"21", "NUM"=>"7", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"21", "NUM"=>"8", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"21", "NUM"=>"9", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"21", "NUM"=>"10", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"21", "NUM"=>"11", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"21", "NUM"=>"12", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"21", "NUM"=>"13", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"21", "NUM"=>"14", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"21", "NUM"=>"15", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"21", "NUM"=>"16", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"21", "NUM"=>"17", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"21", "NUM"=>"18", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"21", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"21", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"21", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"21", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"21", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"21", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"21", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"21", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"21", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"21", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
		),
		array(
			array("RYAD"=>"20", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"20", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"20", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"20", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"20", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"20", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"20", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"20", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"20", "NUM"=>"1", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"20", "NUM"=>"2", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"20", "NUM"=>"3", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"20", "NUM"=>"4", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"20", "NUM"=>"5", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"20", "NUM"=>"6", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"20", "NUM"=>"7", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"20", "NUM"=>"8", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"20", "NUM"=>"9", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"20", "NUM"=>"10", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"20", "NUM"=>"11", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"20", "NUM"=>"12", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"20", "NUM"=>"13", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"20", "NUM"=>"14", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"20", "NUM"=>"15", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"20", "NUM"=>"16", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"20", "NUM"=>"17", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"20", "NUM"=>"18", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"20", "NUM"=>"19", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"20", "NUM"=>"20", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"20", "NUM"=>"21", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"20", "NUM"=>"22", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"20", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"20", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"20", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"20", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"20", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"20", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"20", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"20", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
		),
		array(
			array("RYAD"=>"19", "NUM"=>"1", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"19", "NUM"=>"2", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"19", "NUM"=>"3", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"19", "NUM"=>"4", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"19", "NUM"=>"5", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"19", "NUM"=>"6", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"19", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"19", "NUM"=>"7", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"19", "NUM"=>"8", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"19", "NUM"=>"9", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"19", "NUM"=>"10", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"19", "NUM"=>"11", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"19", "NUM"=>"12", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"19", "NUM"=>"13", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"19", "NUM"=>"14", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"19", "NUM"=>"15", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"19", "NUM"=>"16", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"19", "NUM"=>"17", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"19", "NUM"=>"18", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"19", "NUM"=>"19", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"19", "NUM"=>"20", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"19", "NUM"=>"21", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"19", "NUM"=>"22", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"19", "NUM"=>"23", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"19", "NUM"=>"24", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"19", "NUM"=>"25", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"19", "NUM"=>"26", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"19", "NUM"=>"27", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"19", "NUM"=>"28", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"19", "NUM"=>"29", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"19", "NUM"=>"30", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"19", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"19", "NUM"=>"31", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"19", "NUM"=>"32", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"19", "NUM"=>"33", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"19", "NUM"=>"34", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"19", "NUM"=>"35", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"19", "NUM"=>"36", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
		),
		array(
			array("RYAD"=>"18", "NUM"=>"1", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"18", "NUM"=>"2", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"18", "NUM"=>"3", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"18", "NUM"=>"4", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"18", "NUM"=>"5", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"18", "NUM"=>"6", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"18", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"18", "NUM"=>"7", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"18", "NUM"=>"8", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"18", "NUM"=>"9", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"18", "NUM"=>"10", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"18", "NUM"=>"11", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"18", "NUM"=>"12", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"18", "NUM"=>"13", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"18", "NUM"=>"14", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"18", "NUM"=>"15", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"18", "NUM"=>"16", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"18", "NUM"=>"17", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"18", "NUM"=>"18", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"18", "NUM"=>"19", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"18", "NUM"=>"20", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"18", "NUM"=>"21", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"18", "NUM"=>"22", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"18", "NUM"=>"23", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"18", "NUM"=>"24", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"18", "NUM"=>"25", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"18", "NUM"=>"26", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"18", "NUM"=>"27", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"18", "NUM"=>"28", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"18", "NUM"=>"29", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"18", "NUM"=>"30", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"18", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"18", "NUM"=>"31", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"18", "NUM"=>"32", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"18", "NUM"=>"33", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"18", "NUM"=>"34", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"18", "NUM"=>"35", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"18", "NUM"=>"36", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
		),
		array(
			array("RYAD"=>"17", "NUM"=>"1", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"17", "NUM"=>"2", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"17", "NUM"=>"3", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"17", "NUM"=>"4", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"17", "NUM"=>"5", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"17", "NUM"=>"6", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"17", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"17", "NUM"=>"7", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"17", "NUM"=>"8", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"17", "NUM"=>"9", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"17", "NUM"=>"10", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"17", "NUM"=>"11", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"17", "NUM"=>"12", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"17", "NUM"=>"13", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"17", "NUM"=>"14", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"17", "NUM"=>"15", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"17", "NUM"=>"16", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"17", "NUM"=>"17", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"17", "NUM"=>"18", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"17", "NUM"=>"19", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"17", "NUM"=>"20", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"17", "NUM"=>"21", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"17", "NUM"=>"22", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"17", "NUM"=>"23", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"17", "NUM"=>"24", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"17", "NUM"=>"25", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"17", "NUM"=>"26", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"17", "NUM"=>"27", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"17", "NUM"=>"28", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"17", "NUM"=>"29", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"17", "NUM"=>"30", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"17", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"17", "NUM"=>"31", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"17", "NUM"=>"32", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"17", "NUM"=>"33", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"17", "NUM"=>"34", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"17", "NUM"=>"35", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"17", "NUM"=>"36", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
		),
		array(
			array("RYAD"=>"16", "NUM"=>"1", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"16", "NUM"=>"2", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"16", "NUM"=>"3", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"16", "NUM"=>"4", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"16", "NUM"=>"5", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"16", "NUM"=>"6", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"16", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"16", "NUM"=>"7", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"16", "NUM"=>"8", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"16", "NUM"=>"9", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"16", "NUM"=>"10", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"16", "NUM"=>"11", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"16", "NUM"=>"12", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"16", "NUM"=>"13", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"16", "NUM"=>"14", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"16", "NUM"=>"15", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"16", "NUM"=>"16", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"16", "NUM"=>"17", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"16", "NUM"=>"18", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"16", "NUM"=>"19", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"16", "NUM"=>"20", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"16", "NUM"=>"21", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"16", "NUM"=>"22", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"16", "NUM"=>"23", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"16", "NUM"=>"24", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"16", "NUM"=>"25", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"16", "NUM"=>"26", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"16", "NUM"=>"27", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"16", "NUM"=>"28", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"16", "NUM"=>"29", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"16", "NUM"=>"30", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"16", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"16", "NUM"=>"31", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"16", "NUM"=>"32", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"16", "NUM"=>"33", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"16", "NUM"=>"34", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"16", "NUM"=>"35", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"16", "NUM"=>"36", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
		),
		array(
			array("RYAD"=>"15", "NUM"=>"1", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"15", "NUM"=>"2", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"15", "NUM"=>"3", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"15", "NUM"=>"4", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"15", "NUM"=>"5", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"15", "NUM"=>"6", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"15", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"15", "NUM"=>"7", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"15", "NUM"=>"8", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"15", "NUM"=>"9", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"15", "NUM"=>"10", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"15", "NUM"=>"11", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"15", "NUM"=>"12", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"15", "NUM"=>"13", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"15", "NUM"=>"14", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"15", "NUM"=>"15", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"15", "NUM"=>"16", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"15", "NUM"=>"17", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"15", "NUM"=>"18", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"15", "NUM"=>"19", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"15", "NUM"=>"20", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"15", "NUM"=>"21", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"15", "NUM"=>"22", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"15", "NUM"=>"23", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"15", "NUM"=>"24", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"15", "NUM"=>"25", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"15", "NUM"=>"26", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"15", "NUM"=>"27", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"15", "NUM"=>"28", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"15", "NUM"=>"29", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"15", "NUM"=>"30", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"15", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"15", "NUM"=>"31", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"15", "NUM"=>"32", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"15", "NUM"=>"33", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"15", "NUM"=>"34", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"15", "NUM"=>"35", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"15", "NUM"=>"36", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
		),



		array(
			array("RYAD"=>"EMPTY", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR", "COLSPAN"=>"8"),
			array("RYAD"=>"EMPTY", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR", "COLSPAN"=>"22"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR", "COLSPAN"=>"8"),
		),



		array(
			array("RYAD"=>"14", "NUM"=>"1", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"14", "NUM"=>"2", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"14", "NUM"=>"3", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"14", "NUM"=>"4", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"14", "NUM"=>"5", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"14", "NUM"=>"6", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"EMPTY", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR", "COLSPAN"=>"2"),
			array("RYAD"=>"ПАРТЕР", "NUM"=>"PRINT_DATA", "TYPE_PLACE"=>"AMFITEATR", "COLSPAN"=>"22"),
			array("RYAD"=>"EMPTY", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR", "COLSPAN"=>"2"),
/*			array("RYAD"=>"18", "NUM"=>"3", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"18", "NUM"=>"4", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"18", "NUM"=>"5", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"18", "NUM"=>"6", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"18", "NUM"=>"7", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"18", "NUM"=>"8", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"18", "NUM"=>"9", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"18", "NUM"=>"10", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"18", "NUM"=>"11", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"18", "NUM"=>"12", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"18", "NUM"=>"13", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"18", "NUM"=>"14", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"18", "NUM"=>"15", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"18", "NUM"=>"16", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"18", "NUM"=>"17", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"18", "NUM"=>"18", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"18", "NUM"=>"19", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"18", "NUM"=>"20", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"18", "NUM"=>"PRINT_DATA", "TYPE_PLACE"=>"AMFITEATR"),*/
			array("RYAD"=>"14", "NUM"=>"7", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"14", "NUM"=>"8", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"14", "NUM"=>"9", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"14", "NUM"=>"10", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"14", "NUM"=>"11", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"14", "NUM"=>"12", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
		),

		array(
			array("RYAD"=>"13", "NUM"=>"1", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"13", "NUM"=>"2", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"13", "NUM"=>"3", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"13", "NUM"=>"4", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"13", "NUM"=>"5", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"13", "NUM"=>"6", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
/*			array("RYAD"=>"17", "NUM"=>"2", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"17", "NUM"=>"3", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"17", "NUM"=>"4", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"17", "NUM"=>"5", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"17", "NUM"=>"6", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"17", "NUM"=>"7", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"17", "NUM"=>"8", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"17", "NUM"=>"9", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"17", "NUM"=>"10", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"17", "NUM"=>"11", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"17", "NUM"=>"12", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"17", "NUM"=>"13", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"17", "NUM"=>"14", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"17", "NUM"=>"15", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"17", "NUM"=>"16", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"17", "NUM"=>"17", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"17", "NUM"=>"18", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"17", "NUM"=>"19", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"17", "NUM"=>"20", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"17", "NUM"=>"21", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"17", "NUM"=>"PRINT_DATA", "TYPE_PLACE"=>"AMFITEATR"),*/
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"13", "NUM"=>"7", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"13", "NUM"=>"8", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"13", "NUM"=>"9", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"13", "NUM"=>"10", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"13", "NUM"=>"11", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"13", "NUM"=>"12", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
		),

		array(
			array("RYAD"=>"12", "NUM"=>"1", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"12", "NUM"=>"2", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"12", "NUM"=>"3", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"12", "NUM"=>"4", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"12", "NUM"=>"5", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"12", "NUM"=>"6", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"16", "NUM"=>"1", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"16", "NUM"=>"2", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"16", "NUM"=>"3", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"16", "NUM"=>"4", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"16", "NUM"=>"5", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"16", "NUM"=>"6", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"16", "NUM"=>"7", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"16", "NUM"=>"8", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"16", "NUM"=>"9", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"16", "NUM"=>"10", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"16", "NUM"=>"11", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"16", "NUM"=>"12", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"16", "NUM"=>"13", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"16", "NUM"=>"14", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"16", "NUM"=>"15", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"16", "NUM"=>"16", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"16", "NUM"=>"17", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"16", "NUM"=>"18", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"16", "NUM"=>"19", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"16", "NUM"=>"20", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"16", "NUM"=>"21", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"16", "NUM"=>"22", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"16", "NUM"=>"PRINT_DATA", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"12", "NUM"=>"7", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"12", "NUM"=>"8", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"12", "NUM"=>"9", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"12", "NUM"=>"10", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"12", "NUM"=>"11", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"12", "NUM"=>"12", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
		),




		array(
			array("RYAD"=>"11", "NUM"=>"1", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"11", "NUM"=>"2", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"11", "NUM"=>"3", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"11", "NUM"=>"4", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"11", "NUM"=>"5", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"11", "NUM"=>"6", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"15", "NUM"=>"1", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"15", "NUM"=>"2", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"15", "NUM"=>"3", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"15", "NUM"=>"4", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"15", "NUM"=>"5", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"15", "NUM"=>"6", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"15", "NUM"=>"7", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"15", "NUM"=>"8", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"15", "NUM"=>"9", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"15", "NUM"=>"10", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"15", "NUM"=>"11", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"15", "NUM"=>"12", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"15", "NUM"=>"13", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"15", "NUM"=>"14", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"15", "NUM"=>"15", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"15", "NUM"=>"16", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"15", "NUM"=>"17", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"15", "NUM"=>"18", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"15", "NUM"=>"19", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"15", "NUM"=>"20", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"15", "NUM"=>"21", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"15", "NUM"=>"22", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"15", "NUM"=>"PRINT_DATA", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"11", "NUM"=>"7", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"11", "NUM"=>"8", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"11", "NUM"=>"9", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"11", "NUM"=>"10", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"11", "NUM"=>"11", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"11", "NUM"=>"12", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
		),
		array(
			array("RYAD"=>"10", "NUM"=>"1", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"10", "NUM"=>"2", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"10", "NUM"=>"3", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"10", "NUM"=>"4", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"10", "NUM"=>"5", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"10", "NUM"=>"6", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"14", "NUM"=>"1", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"14", "NUM"=>"2", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"14", "NUM"=>"3", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"14", "NUM"=>"4", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"14", "NUM"=>"5", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"14", "NUM"=>"6", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"14", "NUM"=>"7", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"14", "NUM"=>"8", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"14", "NUM"=>"9", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"14", "NUM"=>"10", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"14", "NUM"=>"11", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"14", "NUM"=>"12", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"14", "NUM"=>"13", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"14", "NUM"=>"14", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"14", "NUM"=>"15", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"14", "NUM"=>"16", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"14", "NUM"=>"17", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"14", "NUM"=>"18", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"14", "NUM"=>"19", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"14", "NUM"=>"20", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"14", "NUM"=>"21", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"14", "NUM"=>"22", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"14", "NUM"=>"PRINT_DATA", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"10", "NUM"=>"7", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"10", "NUM"=>"8", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"10", "NUM"=>"9", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"10", "NUM"=>"10", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"10", "NUM"=>"11", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"10", "NUM"=>"12", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
		),
		array(
			array("RYAD"=>"9", "NUM"=>"1", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"9", "NUM"=>"2", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"9", "NUM"=>"3", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"9", "NUM"=>"4", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"9", "NUM"=>"5", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"9", "NUM"=>"6", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"13", "NUM"=>"1", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"13", "NUM"=>"2", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"13", "NUM"=>"3", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"13", "NUM"=>"4", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"13", "NUM"=>"5", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"13", "NUM"=>"6", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"13", "NUM"=>"7", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"13", "NUM"=>"8", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"13", "NUM"=>"9", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"13", "NUM"=>"10", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"13", "NUM"=>"11", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"13", "NUM"=>"12", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"13", "NUM"=>"13", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"13", "NUM"=>"14", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"13", "NUM"=>"15", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"13", "NUM"=>"16", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"13", "NUM"=>"17", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"13", "NUM"=>"18", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"13", "NUM"=>"19", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"13", "NUM"=>"20", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"13", "NUM"=>"21", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"13", "NUM"=>"22", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"13", "NUM"=>"PRINT_DATA", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"9", "NUM"=>"7", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"9", "NUM"=>"8", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"9", "NUM"=>"9", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"9", "NUM"=>"10", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"9", "NUM"=>"11", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"9", "NUM"=>"12", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
		),
		array(
			array("RYAD"=>"8", "NUM"=>"1", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"8", "NUM"=>"2", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"8", "NUM"=>"3", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"8", "NUM"=>"4", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"8", "NUM"=>"5", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"8", "NUM"=>"6", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"12", "NUM"=>"1", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"12", "NUM"=>"2", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"12", "NUM"=>"3", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"12", "NUM"=>"4", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"12", "NUM"=>"5", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"12", "NUM"=>"6", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"12", "NUM"=>"7", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"12", "NUM"=>"8", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"12", "NUM"=>"9", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"12", "NUM"=>"10", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"12", "NUM"=>"11", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"12", "NUM"=>"12", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"12", "NUM"=>"13", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"12", "NUM"=>"14", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"12", "NUM"=>"15", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"12", "NUM"=>"16", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"12", "NUM"=>"17", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"12", "NUM"=>"18", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"12", "NUM"=>"19", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"12", "NUM"=>"20", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"12", "NUM"=>"21", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"12", "NUM"=>"22", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"12", "NUM"=>"PRINT_DATA", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"8", "NUM"=>"7", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"8", "NUM"=>"8", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"8", "NUM"=>"9", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"8", "NUM"=>"10", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"8", "NUM"=>"11", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"8", "NUM"=>"12", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
		),
		array(
			array("RYAD"=>"7", "NUM"=>"1", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"7", "NUM"=>"2", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"7", "NUM"=>"3", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"7", "NUM"=>"4", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"7", "NUM"=>"5", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"7", "NUM"=>"6", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"11", "NUM"=>"1", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"11", "NUM"=>"2", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"11", "NUM"=>"3", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"11", "NUM"=>"4", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"11", "NUM"=>"5", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"11", "NUM"=>"6", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"11", "NUM"=>"7", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"11", "NUM"=>"8", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"11", "NUM"=>"9", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"11", "NUM"=>"10", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"11", "NUM"=>"11", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"11", "NUM"=>"12", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"11", "NUM"=>"13", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"11", "NUM"=>"14", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"11", "NUM"=>"15", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"11", "NUM"=>"16", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"11", "NUM"=>"17", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"11", "NUM"=>"18", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"11", "NUM"=>"19", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"11", "NUM"=>"20", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"11", "NUM"=>"21", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"11", "NUM"=>"22", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"11", "NUM"=>"PRINT_DATA", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"7", "NUM"=>"7", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"7", "NUM"=>"8", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"7", "NUM"=>"9", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"7", "NUM"=>"10", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"7", "NUM"=>"11", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"7", "NUM"=>"12", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
		),
		array(
			array("RYAD"=>"6", "NUM"=>"1", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"6", "NUM"=>"2", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"6", "NUM"=>"3", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"6", "NUM"=>"4", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"6", "NUM"=>"5", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"6", "NUM"=>"6", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"10", "NUM"=>"1", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"10", "NUM"=>"2", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"10", "NUM"=>"3", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"10", "NUM"=>"4", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"10", "NUM"=>"5", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"10", "NUM"=>"6", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"10", "NUM"=>"7", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"10", "NUM"=>"8", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"10", "NUM"=>"9", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"10", "NUM"=>"10", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"10", "NUM"=>"11", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"10", "NUM"=>"12", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"10", "NUM"=>"13", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"10", "NUM"=>"14", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"10", "NUM"=>"15", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"10", "NUM"=>"16", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"10", "NUM"=>"17", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"10", "NUM"=>"18", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"10", "NUM"=>"19", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"10", "NUM"=>"20", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"10", "NUM"=>"21", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"10", "NUM"=>"22", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"10", "NUM"=>"PRINT_DATA", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"6", "NUM"=>"7", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"6", "NUM"=>"8", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"6", "NUM"=>"9", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"6", "NUM"=>"10", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"6", "NUM"=>"11", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"6", "NUM"=>"12", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
		),
		array(
			array("RYAD"=>"5", "NUM"=>"1", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"5", "NUM"=>"2", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"5", "NUM"=>"3", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"5", "NUM"=>"4", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"5", "NUM"=>"5", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"5", "NUM"=>"6", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"9", "NUM"=>"1", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"9", "NUM"=>"2", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"9", "NUM"=>"3", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"9", "NUM"=>"4", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"9", "NUM"=>"5", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"9", "NUM"=>"6", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"9", "NUM"=>"7", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"9", "NUM"=>"8", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"9", "NUM"=>"9", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"9", "NUM"=>"10", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"9", "NUM"=>"11", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"9", "NUM"=>"12", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"9", "NUM"=>"13", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"9", "NUM"=>"14", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"9", "NUM"=>"15", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"9", "NUM"=>"16", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"9", "NUM"=>"17", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"9", "NUM"=>"18", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"9", "NUM"=>"19", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"9", "NUM"=>"20", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"9", "NUM"=>"21", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"9", "NUM"=>"22", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"9", "NUM"=>"PRINT_DATA", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"5", "NUM"=>"7", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"5", "NUM"=>"8", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"5", "NUM"=>"9", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"5", "NUM"=>"10", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"5", "NUM"=>"11", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"5", "NUM"=>"12", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
		),
		array(
			array("RYAD"=>"4", "NUM"=>"1", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"4", "NUM"=>"2", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"4", "NUM"=>"3", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"4", "NUM"=>"4", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"4", "NUM"=>"5", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"4", "NUM"=>"6", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"8", "NUM"=>"1", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"8", "NUM"=>"2", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"8", "NUM"=>"3", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"8", "NUM"=>"4", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"8", "NUM"=>"5", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"8", "NUM"=>"6", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"8", "NUM"=>"7", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"8", "NUM"=>"8", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"8", "NUM"=>"9", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"8", "NUM"=>"10", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"8", "NUM"=>"11", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"8", "NUM"=>"12", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"8", "NUM"=>"13", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"8", "NUM"=>"14", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"8", "NUM"=>"15", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"8", "NUM"=>"16", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"8", "NUM"=>"17", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"8", "NUM"=>"18", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"8", "NUM"=>"19", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"8", "NUM"=>"20", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"8", "NUM"=>"21", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"8", "NUM"=>"22", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"8", "NUM"=>"PRINT_DATA", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"4", "NUM"=>"7", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"4", "NUM"=>"8", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"4", "NUM"=>"9", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"4", "NUM"=>"10", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"4", "NUM"=>"11", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"4", "NUM"=>"12", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
		),
		array(
			array("RYAD"=>"3", "NUM"=>"1", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"3", "NUM"=>"2", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"3", "NUM"=>"3", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"3", "NUM"=>"4", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"3", "NUM"=>"5", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"3", "NUM"=>"6", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"7", "NUM"=>"1", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"7", "NUM"=>"2", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"7", "NUM"=>"3", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"7", "NUM"=>"4", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"7", "NUM"=>"5", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"7", "NUM"=>"6", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"7", "NUM"=>"7", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"7", "NUM"=>"8", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"7", "NUM"=>"9", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"7", "NUM"=>"10", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"7", "NUM"=>"11", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"7", "NUM"=>"12", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"7", "NUM"=>"13", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"7", "NUM"=>"14", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"7", "NUM"=>"15", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"7", "NUM"=>"16", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"7", "NUM"=>"17", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"7", "NUM"=>"18", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"7", "NUM"=>"19", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"7", "NUM"=>"20", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"7", "NUM"=>"21", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"7", "NUM"=>"22", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"7", "NUM"=>"PRINT_DATA", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"3", "NUM"=>"7", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"3", "NUM"=>"8", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"3", "NUM"=>"9", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"3", "NUM"=>"10", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"3", "NUM"=>"11", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"3", "NUM"=>"12", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
		),
		array(
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"2", "NUM"=>"1", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"2", "NUM"=>"2", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"2", "NUM"=>"3", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"2", "NUM"=>"4", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"2", "NUM"=>"5", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"6", "NUM"=>"1", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"6", "NUM"=>"2", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"6", "NUM"=>"3", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"6", "NUM"=>"4", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"6", "NUM"=>"5", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"6", "NUM"=>"6", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"6", "NUM"=>"7", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"6", "NUM"=>"8", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"6", "NUM"=>"9", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"6", "NUM"=>"10", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"6", "NUM"=>"11", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"6", "NUM"=>"12", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"6", "NUM"=>"13", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"6", "NUM"=>"14", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"6", "NUM"=>"15", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"6", "NUM"=>"16", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"6", "NUM"=>"17", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"6", "NUM"=>"18", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"6", "NUM"=>"19", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"6", "NUM"=>"20", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"6", "NUM"=>"21", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"6", "NUM"=>"22", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"6", "NUM"=>"PRINT_DATA", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"2", "NUM"=>"6", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"2", "NUM"=>"7", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"2", "NUM"=>"8", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"2", "NUM"=>"9", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"2", "NUM"=>"10", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"2", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
		),
		array(
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"1", "NUM"=>"1", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"1", "NUM"=>"2", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"1", "NUM"=>"3", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"5", "NUM"=>"1", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"5", "NUM"=>"2", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"5", "NUM"=>"3", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"5", "NUM"=>"4", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"5", "NUM"=>"5", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"5", "NUM"=>"6", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"5", "NUM"=>"7", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"5", "NUM"=>"8", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"5", "NUM"=>"9", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"5", "NUM"=>"10", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"5", "NUM"=>"11", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"5", "NUM"=>"12", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"5", "NUM"=>"13", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"5", "NUM"=>"14", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"5", "NUM"=>"15", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"5", "NUM"=>"16", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"5", "NUM"=>"17", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"5", "NUM"=>"18", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"5", "NUM"=>"19", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"5", "NUM"=>"20", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"5", "NUM"=>"21", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"5", "NUM"=>"22", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"5", "NUM"=>"PRINT_DATA", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"1", "NUM"=>"4", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"1", "NUM"=>"5", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"1", "NUM"=>"6", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"1", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
		),

		array(
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"4", "NUM"=>"1", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"4", "NUM"=>"2", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"4", "NUM"=>"3", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"4", "NUM"=>"4", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"4", "NUM"=>"5", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"4", "NUM"=>"6", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"4", "NUM"=>"7", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"4", "NUM"=>"8", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"4", "NUM"=>"9", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"4", "NUM"=>"10", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"4", "NUM"=>"11", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"4", "NUM"=>"12", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"4", "NUM"=>"13", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"4", "NUM"=>"14", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"4", "NUM"=>"15", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"4", "NUM"=>"16", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"4", "NUM"=>"17", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"4", "NUM"=>"18", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"4", "NUM"=>"19", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"4", "NUM"=>"20", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"4", "NUM"=>"21", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"4", "NUM"=>"22", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"4", "NUM"=>"PRINT_DATA", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
		),

		array(
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"3", "NUM"=>"1", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"3", "NUM"=>"2", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"3", "NUM"=>"3", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"3", "NUM"=>"4", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"3", "NUM"=>"5", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"3", "NUM"=>"6", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"3", "NUM"=>"7", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"3", "NUM"=>"8", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"3", "NUM"=>"9", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"3", "NUM"=>"10", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"3", "NUM"=>"11", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"3", "NUM"=>"12", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"3", "NUM"=>"13", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"3", "NUM"=>"14", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"3", "NUM"=>"15", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"3", "NUM"=>"16", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"3", "NUM"=>"17", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"3", "NUM"=>"18", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"3", "NUM"=>"19", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"3", "NUM"=>"20", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"3", "NUM"=>"21", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"3", "NUM"=>"22", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"3", "NUM"=>"PRINT_DATA", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
		),

		array(
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"2", "NUM"=>"1", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"2", "NUM"=>"2", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"2", "NUM"=>"3", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"2", "NUM"=>"4", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"2", "NUM"=>"5", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"2", "NUM"=>"6", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"2", "NUM"=>"7", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"2", "NUM"=>"8", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"2", "NUM"=>"9", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"2", "NUM"=>"10", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"2", "NUM"=>"11", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"2", "NUM"=>"12", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"2", "NUM"=>"13", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"2", "NUM"=>"14", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"2", "NUM"=>"15", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"2", "NUM"=>"16", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"2", "NUM"=>"17", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"2", "NUM"=>"18", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"2", "NUM"=>"19", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"2", "NUM"=>"20", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"2", "NUM"=>"21", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"2", "NUM"=>"22", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"2", "NUM"=>"PRINT_DATA", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
		),

		array(
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"1", "NUM"=>"1", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"1", "NUM"=>"2", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"1", "NUM"=>"3", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"1", "NUM"=>"4", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"1", "NUM"=>"5", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"1", "NUM"=>"6", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"1", "NUM"=>"7", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"1", "NUM"=>"8", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"1", "NUM"=>"9", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"1", "NUM"=>"10", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"1", "NUM"=>"11", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"1", "NUM"=>"12", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"1", "NUM"=>"13", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"1", "NUM"=>"14", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"1", "NUM"=>"15", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"1", "NUM"=>"16", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"1", "NUM"=>"17", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"1", "NUM"=>"18", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"1", "NUM"=>"19", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"1", "NUM"=>"20", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"1", "NUM"=>"21", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"1", "NUM"=>"22", "TYPE"=>"VIP", "COST"=>"1500", "QUOTA"=>"", "TYPE_PLACE"=>"PARTER"),
			array("RYAD"=>"1", "NUM"=>"PRINT_DATA", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
			array("RYAD"=>"", "NUM"=>"EMPTY", "TYPE_PLACE"=>"AMFITEATR"),
		),


	);
?>