<?php
global $SHEMA;
/*
балкон - весь Стандарт, 650 руб.
партер: Делюкс 750 руб. - в левой части все 1,2,3 места; в правой - с первого места и вверх:
22,23
24,25
26,27
26,27,28
28,29,30
30,31,32
30,31,32
32, 33, 34 (5 рядов вверх) - 32,33,34,35,36.

Все остальные места VIP 850 руб.

tatiana-mazina 20:36
теперь по квотам: 1/5/9/13/14 и 1ый ряд балкона - билеты Театра,
2/6/10 и 2ой ряд балкона - parter.ru,
2/7/11 и 3ий ряд балкона - concert.ru,
4/8/12 и 4ый ряд - ticketland.ru

*/


$SHEMA = array(
"BALKON"=> array(
				"NAME"=>"БАЛКОН",
				"PLACE"=>array(
				"4"=>array(
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"1","TYPE"=>"","COST"=>"650", "QUOTA"=>"concert.ru"),
							array("NUM"=>"2","TYPE"=>"","COST"=>"650", "QUOTA"=>"concert.ru"),
							array("NUM"=>"3","TYPE"=>"","COST"=>"650", "QUOTA"=>"concert.ru"),
							array("NUM"=>"4","TYPE"=>"","COST"=>"650", "QUOTA"=>"concert.ru"),
							array("NUM"=>"5","TYPE"=>"","COST"=>"650", "QUOTA"=>"concert.ru"),
							array("NUM"=>"6","TYPE"=>"","COST"=>"650", "QUOTA"=>"concert.ru"),
							array("NUM"=>"7","TYPE"=>"","COST"=>"650", "QUOTA"=>"concert.ru"),
							array("NUM"=>"8","TYPE"=>"","COST"=>"650", "QUOTA"=>"concert.ru"),
							array("NUM"=>"9","TYPE"=>"","COST"=>"650", "QUOTA"=>"concert.ru"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"10","TYPE"=>"","COST"=>"650", "QUOTA"=>"parter.ru"),
							array("NUM"=>"11","TYPE"=>"","COST"=>"650", "QUOTA"=>"parter.ru"),
							array("NUM"=>"12","TYPE"=>"","COST"=>"650", "QUOTA"=>"parter.ru"),
							array("NUM"=>"13","TYPE"=>"","COST"=>"650", "QUOTA"=>"parter.ru"),
							array("NUM"=>"14","TYPE"=>"","COST"=>"650", "QUOTA"=>"parter.ru"),
							array("NUM"=>"15","TYPE"=>"","COST"=>"650", "QUOTA"=>"parter.ru"),
							array("NUM"=>"16","TYPE"=>"","COST"=>"650", "QUOTA"=>"parter.ru"),
							array("NUM"=>"17","TYPE"=>"","COST"=>"650", "QUOTA"=>"parter.ru"),
							array("NUM"=>"18","TYPE"=>"","COST"=>"650", "QUOTA"=>"parter.ru"),
							array("NUM"=>"19","TYPE"=>"","COST"=>"650", "QUOTA"=>"parter.ru"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"20","TYPE"=>"","COST"=>"650", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"21","TYPE"=>"","COST"=>"650", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"22","TYPE"=>"","COST"=>"650", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"23","TYPE"=>"","COST"=>"650", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"24","TYPE"=>"","COST"=>"650", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"25","TYPE"=>"","COST"=>"650", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"26","TYPE"=>"","COST"=>"650", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"27","TYPE"=>"","COST"=>"650", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"28","TYPE"=>"","COST"=>"650", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
				),
				"3"=>array(
							array("NUM"=>"EMPTY"),
							array("NUM"=>"1","TYPE"=>"","COST"=>"650", "QUOTA"=>"concert.ru"),
							array("NUM"=>"2","TYPE"=>"","COST"=>"650", "QUOTA"=>"concert.ru"),
							array("NUM"=>"3","TYPE"=>"","COST"=>"650", "QUOTA"=>"concert.ru"),
							array("NUM"=>"4","TYPE"=>"","COST"=>"650", "QUOTA"=>"concert.ru"),
							array("NUM"=>"5","TYPE"=>"","COST"=>"650", "QUOTA"=>"concert.ru"),
							array("NUM"=>"6","TYPE"=>"","COST"=>"650", "QUOTA"=>"concert.ru"),
							array("NUM"=>"7","TYPE"=>"","COST"=>"650", "QUOTA"=>"concert.ru"),
							array("NUM"=>"8","TYPE"=>"","COST"=>"650", "QUOTA"=>"concert.ru"),
							array("NUM"=>"9","TYPE"=>"","COST"=>"650", "QUOTA"=>"concert.ru"),
							array("NUM"=>"10","TYPE"=>"","COST"=>"650", "QUOTA"=>"concert.ru"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"11","TYPE"=>"","COST"=>"650", "QUOTA"=>"parter.ru"),
							array("NUM"=>"12","TYPE"=>"","COST"=>"650", "QUOTA"=>"parter.ru"),
							array("NUM"=>"13","TYPE"=>"","COST"=>"650", "QUOTA"=>"parter.ru"),
							array("NUM"=>"14","TYPE"=>"","COST"=>"650", "QUOTA"=>"parter.ru"),
							array("NUM"=>"15","TYPE"=>"","COST"=>"650", "QUOTA"=>"parter.ru"),
							array("NUM"=>"16","TYPE"=>"","COST"=>"650", "QUOTA"=>"parter.ru"),
							array("NUM"=>"17","TYPE"=>"","COST"=>"650", "QUOTA"=>"parter.ru"),
							array("NUM"=>"18","TYPE"=>"","COST"=>"650", "QUOTA"=>"parter.ru"),
							array("NUM"=>"19","TYPE"=>"","COST"=>"650", "QUOTA"=>"parter.ru"),
							array("NUM"=>"20","TYPE"=>"","COST"=>"650", "QUOTA"=>"parter.ru"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"21","TYPE"=>"","COST"=>"650", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"22","TYPE"=>"","COST"=>"650", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"23","TYPE"=>"","COST"=>"650", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"24","TYPE"=>"","COST"=>"650", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"25","TYPE"=>"","COST"=>"650", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"26","TYPE"=>"","COST"=>"650", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"27","TYPE"=>"","COST"=>"650", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"28","TYPE"=>"","COST"=>"650", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"29","TYPE"=>"","COST"=>"650", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
				),
				"2"=>array(
							array("NUM"=>"EMPTY"),
							array("NUM"=>"1","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"2","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"3","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"4","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"5","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"6","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"7","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"8","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"9","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"10","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"11","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"12","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"13","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"14","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"15","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"16","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"17","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"18","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"19","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"20","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"21","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"22","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"23","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"24","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"25","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"26","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"27","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"28","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"29","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"30","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
				),
				"1"=>array(
							array("NUM"=>"1","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"2","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"3","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"4","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"5","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"6","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"7","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"8","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"9","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"10","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"11","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"12","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"13","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"14","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"15","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"16","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"17","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"18","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"19","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"20","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"21","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"22","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"23","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"24","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"25","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"26","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"27","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"28","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"29","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"30","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"31","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"32","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"33","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"34","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"35","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"36","TYPE"=>"","COST"=>"650", "QUOTA"=>""),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
				),
		)
	),

/*балкон - весь Стандарт, 650 руб.
партер: Делюкс 750 руб. - в левой части все 1,2,3 места; в правой - с первого места и вверх: 22,23 - 24,25 - 26,27 - 26,27,28 - 28,29,30 - 30,31,32 - 30,31,32 - 32, 33, 34 (5 рядов вверх) - 32,33,34,35,36.

Все остальные места VIP 850 руб.*/
	"PARTER"=>array(
				"NAME"=>"ПАРТЕР",
				"PLACE"=>array(
				"14"=>array(
							array("NUM"=>"EMPTY",),
							array("NUM"=>"EMPTY",),
							array("NUM"=>"EMPTY",),
							array("NUM"=>"EMPTY",),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"1","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"2","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"3","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"4","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"5","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"6","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"7","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"8","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"9","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"10","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"11","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"12","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"13","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"14","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"15","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"16","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
				),
				"13"=>array(
							array("NUM"=>"1","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>""),
							array("NUM"=>"2","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>""),
							array("NUM"=>"3","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>""),
							array("NUM"=>"4","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"5","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"6","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"7","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"8","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"9","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"10","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"11","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"12","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"13","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"14","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"15","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"16","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"17","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"18","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"19","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"20","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"21","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"22","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"23","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"24","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"25","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"26","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"27","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"28","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"29","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"30","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"31","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"32","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>""),
							array("NUM"=>"33","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>""),
							array("NUM"=>"34","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>""),
							array("NUM"=>"35","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>""),
							array("NUM"=>"36","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>""),
				),
				"12"=>array(
							array("NUM"=>"1","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>"parter.ru"),
							array("NUM"=>"2","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>"parter.ru"),
							array("NUM"=>"3","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>"parter.ru"),
							array("NUM"=>"4","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"parter.ru"),
							array("NUM"=>"5","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"parter.ru"),
							array("NUM"=>"6","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"parter.ru"),
							array("NUM"=>"7","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"parter.ru"),
							array("NUM"=>"8","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"parter.ru"),
							array("NUM"=>"9","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"parter.ru"),
							array("NUM"=>"10","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"parter.ru"),
							array("NUM"=>"11","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"parter.ru"),
							array("NUM"=>"12","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"parter.ru"),
							array("NUM"=>"13","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"parter.ru"),
							array("NUM"=>"14","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"parter.ru"),
							array("NUM"=>"15","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"parter.ru"),
							array("NUM"=>"16","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"parter.ru"),
							array("NUM"=>"17","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"parter.ru"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"18","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"parter.ru"),
							array("NUM"=>"19","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"parter.ru"),
							array("NUM"=>"20","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"parter.ru"),
							array("NUM"=>"21","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"parter.ru"),
							array("NUM"=>"22","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"parter.ru"),
							array("NUM"=>"23","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"parter.ru"),
							array("NUM"=>"24","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"parter.ru"),
							array("NUM"=>"25","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"parter.ru"),
							array("NUM"=>"26","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"parter.ru"),
							array("NUM"=>"27","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"parter.ru"),
							array("NUM"=>"28","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"parter.ru"),
							array("NUM"=>"29","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"parter.ru"),
							array("NUM"=>"30","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"parter.ru"),
							array("NUM"=>"31","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"parter.ru"),
							array("NUM"=>"32","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>"parter.ru"),
							array("NUM"=>"33","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>"parter.ru"),
							array("NUM"=>"34","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>"parter.ru"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
				),
				"11"=>array(
							array("NUM"=>"1","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"2","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"3","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"4","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"5","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"6","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"7","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"8","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"9","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"10","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"11","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"12","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"13","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"14","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"15","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"16","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"17","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"18","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"19","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"20","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"21","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"22","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"23","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"24","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"25","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"26","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"27","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"28","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"29","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"30","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"31","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"32","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"33","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"34","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>"ticketland.ru"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
				),
				"10"=>array(
							array("NUM"=>"1","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>"concert.ru"),
							array("NUM"=>"2","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>"concert.ru"),
							array("NUM"=>"3","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>"concert.ru"),
							array("NUM"=>"4","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"concert.ru"),
							array("NUM"=>"5","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"concert.ru"),
							array("NUM"=>"6","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"concert.ru"),
							array("NUM"=>"7","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"concert.ru"),
							array("NUM"=>"8","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"concert.ru"),
							array("NUM"=>"9","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"concert.ru"),
							array("NUM"=>"10","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"concert.ru"),
							array("NUM"=>"11","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"concert.ru"),
							array("NUM"=>"12","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"concert.ru"),
							array("NUM"=>"13","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"concert.ru"),
							array("NUM"=>"14","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"concert.ru"),
							array("NUM"=>"15","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"concert.ru"),
							array("NUM"=>"16","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"concert.ru"),
							array("NUM"=>"17","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"concert.ru"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"18","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"concert.ru"),
							array("NUM"=>"19","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"concert.ru"),
							array("NUM"=>"20","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"concert.ru"),
							array("NUM"=>"21","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"concert.ru"),
							array("NUM"=>"22","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"concert.ru"),
							array("NUM"=>"23","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"concert.ru"),
							array("NUM"=>"24","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"concert.ru"),
							array("NUM"=>"25","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"concert.ru"),
							array("NUM"=>"26","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"concert.ru"),
							array("NUM"=>"27","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"concert.ru"),
							array("NUM"=>"28","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"concert.ru"),
							array("NUM"=>"29","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"concert.ru"),
							array("NUM"=>"30","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"concert.ru"),
							array("NUM"=>"31","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"concert.ru"),
							array("NUM"=>"32","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>"concert.ru"),
							array("NUM"=>"33","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>"concert.ru"),
							array("NUM"=>"34","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>"concert.ru"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
				),
				"9"=>array(
							array("NUM"=>"1","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>"parter.ru"),
							array("NUM"=>"2","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>"parter.ru"),
							array("NUM"=>"3","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>"parter.ru"),
							array("NUM"=>"4","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"parter.ru"),
							array("NUM"=>"5","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"parter.ru"),
							array("NUM"=>"6","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"parter.ru"),
							array("NUM"=>"7","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"parter.ru"),
							array("NUM"=>"8","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"parter.ru"),
							array("NUM"=>"9","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"parter.ru"),
							array("NUM"=>"10","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"parter.ru"),
							array("NUM"=>"11","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"parter.ru"),
							array("NUM"=>"12","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"parter.ru"),
							array("NUM"=>"13","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"parter.ru"),
							array("NUM"=>"14","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"parter.ru"),
							array("NUM"=>"15","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"parter.ru"),
							array("NUM"=>"16","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"parter.ru"),
							array("NUM"=>"17","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"parter.ru"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"18","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"parter.ru"),
							array("NUM"=>"19","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"parter.ru"),
							array("NUM"=>"20","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"parter.ru"),
							array("NUM"=>"21","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"parter.ru"),
							array("NUM"=>"22","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"parter.ru"),
							array("NUM"=>"23","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"parter.ru"),
							array("NUM"=>"24","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"parter.ru"),
							array("NUM"=>"25","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"parter.ru"),
							array("NUM"=>"26","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"parter.ru"),
							array("NUM"=>"27","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"parter.ru"),
							array("NUM"=>"28","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"parter.ru"),
							array("NUM"=>"29","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"parter.ru"),
							array("NUM"=>"30","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"parter.ru"),
							array("NUM"=>"31","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>"parter.ru"),
							array("NUM"=>"32","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>"parter.ru"),
							array("NUM"=>"33","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>"parter.ru"),
							array("NUM"=>"34","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>"parter.ru"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
				),
				"8"=>array(
							array("NUM"=>"1","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>""),
							array("NUM"=>"2","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>""),
							array("NUM"=>"3","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>""),
							array("NUM"=>"4","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"5","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"6","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"7","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"8","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"9","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"10","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"11","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"12","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"13","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"14","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"15","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"16","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"17","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"18","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"19","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"20","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"21","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"22","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"23","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"24","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"25","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"26","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"27","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"28","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"29","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"30","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"31","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"32","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>""),
							array("NUM"=>"33","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>""),
							array("NUM"=>"34","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>""),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
				),
				"7"=>array(
							array("NUM"=>"EMPTY"),
							array("NUM"=>"1","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>""),
							array("NUM"=>"2","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>""),
							array("NUM"=>"3","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>""),
							array("NUM"=>"4","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"5","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"6","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"7","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"8","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"9","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"10","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"11","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"12","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"13","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"14","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"15","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"16","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"17","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"18","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"19","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"20","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"21","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"22","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"23","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"24","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"25","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"26","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"27","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"28","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"29","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"30","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>""),
							array("NUM"=>"31","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>""),
							array("NUM"=>"32","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>""),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
				),
				"6"=>array(
							array("NUM"=>"EMPTY"),
							array("NUM"=>"1","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>""),
							array("NUM"=>"2","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>""),
							array("NUM"=>"3","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>""),
							array("NUM"=>"4","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"5","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"6","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"7","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"8","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"9","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"10","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"11","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"12","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"13","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"14","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"15","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"16","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"17","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"18","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"19","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"20","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"21","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"22","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"23","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"24","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"25","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"26","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"27","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"28","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"29","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"30","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>""),
							array("NUM"=>"31","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>""),
							array("NUM"=>"32","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>""),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
				),
				"5"=>array(
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"1","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>""),
							array("NUM"=>"2","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>""),
							array("NUM"=>"3","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>""),
							array("NUM"=>"4","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"5","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"6","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"7","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"8","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"9","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"10","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"11","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"12","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"13","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"14","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"15","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"16","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"17","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"18","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"19","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"20","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"21","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"22","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"23","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"24","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"25","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"26","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"27","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"28","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>""),
							array("NUM"=>"29","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>""),
							array("NUM"=>"30","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>""),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
				),
				"4"=>array(
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"1","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>""),
							array("NUM"=>"2","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>""),
							array("NUM"=>"3","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>""),
							array("NUM"=>"4","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"5","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"6","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"7","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"8","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"9","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"10","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"11","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"12","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"13","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"14","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"15","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"16","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"17","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"18","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"19","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"20","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"21","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"22","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"23","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"24","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"25","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"26","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>""),
							array("NUM"=>"27","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>""),
							array("NUM"=>"28","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>""),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
				),
				"3"=>array(
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"1","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>""),
							array("NUM"=>"2","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>""),
							array("NUM"=>"3","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>""),
							array("NUM"=>"4","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"5","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"6","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"7","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"8","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"9","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"10","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"11","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"12","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"13","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"14","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"15","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"16","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"17","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"18","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"19","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"20","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"21","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"22","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"23","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"24","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"25","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"26","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>""),
							array("NUM"=>"27","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>""),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
				),
				"2"=>array(
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"1","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>""),
							array("NUM"=>"2","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>""),
							array("NUM"=>"3","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>""),
							array("NUM"=>"4","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"5","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"6","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"7","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"8","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"9","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"10","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"11","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"12","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"13","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"14","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"15","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"16","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"17","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"18","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"19","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"20","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"21","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"22","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"23","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"24","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>""),
							array("NUM"=>"25","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>""),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
				),
				"1"=>array(
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"1","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>""),
							array("NUM"=>"2","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>""),
							array("NUM"=>"3","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>""),
							array("NUM"=>"4","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"5","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"6","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"7","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"8","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"9","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"10","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"11","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"12","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"13","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"14","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"15","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"16","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"17","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"18","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"19","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"20","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"21","TYPE"=>"VIP","COST"=>"850", "QUOTA"=>""),
							array("NUM"=>"22","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>""),
							array("NUM"=>"23","TYPE"=>"DELUXE","COST"=>"750", "QUOTA"=>""),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
							array("NUM"=>"EMPTY"),
				)
		)
	)
);

?>