<h2><?php echo $this->title; ?></h2>

<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
<br/>
<?php if (count($this->paginator)) : ?>
<table class="table3">
	<thead>
		<tr>
			<th>#</th>
			<th>Дата</th>
			<th>Log Variant</th>
			<th>Пользователь</th>
			<th>Адресс</th>
			<th>Изменеие</th>
		</tr>
	</thead>
	<tbody>

	<?php foreach ($this->paginator as $log) : ?>
		<tr>
			<td><?php echo $log->id; ?></td>
			<td style="white-space: nowrap"><?php echo $log->action_date; ?></td>
			<td><?php echo $log->findParentRow('Application_Model_DbTable_LogVariants')->log_variant ?></td>
			<td><?php echo $log->findParentRow('Application_Model_DbTable_Users')->username ?></td>
			<td><?php echo $log->remote_ip ?></td>
			<td><?php echo $log->log_message ?></td>
		</tr>
	<?php endforeach; ?>
		<tr></tr>
	</tbody>
</table>
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>

<?php else : ?> 

	<p><?php echo 'Логи на данный момент не доступны'; ?></p>


<?php endif; ?>
