<h2><?php echo $this->title; ?></h2>

<a class ="href-button" href="<?php echo $this->url(array('controller' => 'seans', 'action' => 'add'), null, true)?>">Добавить новый сеанс</a>
<br/>
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
<br/>
<?php if (count($this->paginator)) : ?>
<table class="table3">
	<thead>
		<tr>
			<th>#</th>
			<th>Название</th>
			<th>Дата</th>
			<th>Зал</th>
			<th>Порядок мест</th>
			<th>Псевдоним</th>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody>

	<?php foreach ($this->paginator as $seans) : ?>
		<tr>
			<td><?php echo $seans->id; ?></td>
			<td>
				<a class ="href-button" href="<?php echo $this->url(array('controller' => 'seans', 'action' => 'edit', 'id' => $seans->id),null,true)?>">
				<?php echo $seans->name; ?>
				</a>
			</td>
			<td style="white-space: nowrap"><?php echo $seans->date; ?></td>
			<td><?php echo $seans->name_zal . " ({$seans->zal_alias}) "; ?></td>
			<td><?php echo ($seans->is_strickt_seat ? 'Строгий' : 'Свободный') ?></td>
			<td><?php echo $seans->alias; ?></td>
			<td>
				<a class ="href-button" href="<?php echo $this->url(array('controller' => 'seans', 'action' => 'delete', 'id' => $seans->id),null,true)?>">Delete</a>
				<br/>
				<?php if ( 'old' != $seans->alias) : ?>
				<a class ="href-button" href="<?php echo $this->url(array('controller' => 'scheme', 'action' => 'edit', 'seans_id' => $seans->id, 'zal_alias' => $seans->zal_alias),null,true)?>">Править схему</a>
				<br/>
				<a class ="href-button" href="<?php echo $this->url(array('controller' => 'scheme', 'action' => 'viewscheme', 'seans_id' => $seans->id, 'zal_alias' => $seans->zal_alias),null,true)?>">Просмотреть схему</a>
				<?php endif; ?>
			</td>
		</tr>
	<?php endforeach; ?>
		<tr></tr>
	</tbody>
</table>
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>

<?php else : ?> 

	<p><?php echo 'Сеансов пока нет'; ?></p>


<?php endif; ?>
