<h2><?php echo $this->title; ?></h2>

<a class ="href-button" href="<?php echo $this->url(array('controller' => 'users', 'action' => 'add'),null,true)?>">Добавить нового пользователя</a>
<br/>
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
<br/>
<?php if (count($this->paginator)) : ?>
<table class="table3">
	<thead>
		<tr>
			<th>Id</th>
			<th>User Name</th>
			<th>Full Name</th>
			<th>User Email</th>
			<th>User Role</th>
			<th>Activated</th>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody>
	<?php foreach ($this->paginator as $user) : ?>
		<tr>
			<td><?php echo $user->id; ?></td>
			<td>
				<a class ="href-button" href="<?php echo $this->url(array('controller' => 'users', 'action' => 'view', 'id' => $user->id), null,true)?>">
				<?php echo $user->username; ?>
				</a>
			</td>
			<td><?php echo $user->fio; ?></td>
			<td><?php echo $user->email; ?></td>
			<td><?php echo $user->role; ?></td>
			<td><?php echo $user->activated; ?></td>
			<td>
				<a class ="href-button" href="<?php echo $this->url(array('controller' => 'users', 'action' => 'edit', 'id' => $user->id),null,true)?>">Edit</a>
				<a class ="href-button" href="<?php echo $this->url(array('controller' => 'users', 'action' => 'delete', 'id' => $user->id),null,true)?>">Delete</a>
				<?php if ( !$user->activated ) : ?>
					<a class ="href-button" href="<?php echo $this->url(array('controller' => 'users', 'action' => 'activate', 'id' => $user->id),null,true)?>">Activate</a>
					<a class ="href-button" href="<?php echo $this->url(array('controller' => 'users', 'action' => 'resend', 'id' => $user->id),null,true)?>">Resend Activation</a>
				<?php endif; ?>
			</td>
		</tr>
	<?php endforeach; ?>
	</tbody>
</table>

<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>

<?php else : ?> 
	<p><?php echo 'Пользователей пока нет'; ?></p>
<?php endif; ?>
<br/>
